---
version: '3.8'
services:
  myjenkins:
   image: jenkins/jenkins
   ports:
     - 8989:8080
  qaserver:
   image: tomcat
   ports:
     - 8888:8080
   links:
     - myjenkins:jenkins
  prodserver:
   image: tomcat
   ports:
     - 7979:8080
   links:
     - myjenkins:jenkins
     