version: '3.8'
services:
 db:
  image: postgress
  environment:
   POSTGRES_PASSWORD: intelliqit
   POSTGRES_USER: myuser
   POSTGRESS_DB: mydb
 adminer: 
  image:
  ports:
   - 8989:8080
networks:
 default:
  external:
   name: intelliqit

...