---
version: "3.5"
services:
 hub:
  image: selenium/hub
  ports:
   - 4444:4444
  container_name: hub
 chrome: 
  image: selenium/node-edge
  ports:
   - 5901:5900
  links:
   - hub:selenium 
  container_name: chrome
 firefox:
  image: selenium/standalone-firefox
  ports:
   - 5902:5900
  links:
   - hub: selenium
  container_name:  firefox

...
